In [1]:
import pandas as pd
df = pd.read_csv('/Users/swarchol/Research/seal/data/astro/updated_astro.csv')

df.head()

,objid,RUN,RERUN,CAMCOL,FIELD,ID,type,RA,DEC,u,...,TAI_g,TAI_r,TAI_i,TAI_z,CellID,X_centroid,Y_centroid,cluster,UMAP_X,UMAP_Y
0,1.240000e+18,2708,301,1,234,22,6,18.752891,-0.978412,18.18845,...,4512258771,4512258484,4512258556,4512258699,150,75.030612,1331.153061,4,837.416386,47.412605
1,1.240000e+18,2708,301,1,234,36,3,18.748518,-0.973636,14.58587,...,4512258769,4512258483,4512258554,4512258698,138,36.000000,1287.000000,2,1.299069,2025.426137
2,1.240000e+18,2708,301,1,234,53,3,18.745173,-0.956080,24.63399,...,4512258769,4512258482,4512258554,4512258697,216,4.945205,1127.273973,4,1037.416182,520.434153
3,1.240000e+18,2708,301,1,234,57,3,18.748183,-0.954625,24.63132,...,4512258770,4512258483,4512258555,4512258698,154,32.641026,1114.487179,1,1175.808257,779.087352
4,1.240000e+18,2708,301,1,234,70,6,18.747031,-0.913746,15.86924,...,4512258770,4512258483,4512258554,4512258698,117,21.531186,744.499657,4,809.707975,5.608444

In [2]:
# cluster_columns = ['agcluster','kmeans']
# # cluster_columns = ['agcluster']
# config = {
#     "embeddingImageUrl": "http://localhost:8181/files/embedding_image.ome.tif",
#     "embeddingSegmentationUrl": "http://localhost:8181/files/embedding_segmentation.ome.tif",
#     "csvUrl": "http://localhost:8181/files/csv.csv",
#     "clusterColumns": cluster_columns,
#     "imageUrl": "http://localhost:8181/files/image.ome.tif",
#     "segmentationUrl": "http://localhost:8181/files/segmentation.ome.tif"
# }

In [3]:
   # embeddingImageUrl: "http://localhost:8181/data/astro/hybrid.ome.tif",
   #  embeddingSegmentationUrl: "http://localhost:8181/data/astro/hybrid.mask.ome.tif",
   #  csvUrl: "http://localhost:8181/data/astro/updated_astro.csv",
   #  clusterColumns: ["cluster"],
   #  imageUrl: "http://localhost:8181/data/astro/astro.ome.tif",
   #  segmentationUrl: "http://localhost:8181/data/astro/astro_seg_masks.ome.tif",

In [4]:
conf = {
    'embeddingImageUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/hybrid.ome.tif',
    'embeddingSegmentationUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/hybrid.mask.ome.tif',
    'parquetUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/df.parquet',
    'datasetId': 'exemplar-001',
    'csvUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/df.csv',
    'clusterColumns': ['cluster'],
    'imageUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/image.ome.tif',
    'segmentationUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/image.mask.ome.tif',
    'contourUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/contour.json',
    'shapUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/shap.parquet'
  };

In [5]:
from seal import Seal
Seal(df=None, config=conf)

Seal(config={'embeddingImageUrl': 'https://seal-vis.s3.us-east-1.amazonaws.com/exemplar-001/hybrid.ome.tif', 'â€¦

INFO:     Started server process [78596]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8181 (Press CTRL+C to quit)

INFO:     127.0.0.1:61942 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61943 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61944 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61945 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61946 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61947 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61942 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61943 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61944 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61945 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61946 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61947 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61942 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61943 - "POST /selection/exemplar-001 HTTP/1.1" 200 OK